config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :end_users, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]

    resources :post_comments, only: [:destroy]

     get '/search', to: 'searches#search'

  end


  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}




 scope module: :public do
  root to: 'homes#top'
  get "/home/about" => "homes#about"


  get 'end_users/unsubscribe' => 'end_users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'

  #post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  #post 'end_users/guest_sign_in'  => 'end_users/sessions#guest_sign_in'

  resources :end_users, only: [:index, :show, :edit,:update, :destroy] do
  resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  get '/search', to: 'searches#search'

  post '/guests/guest_sign_in', to: 'guests#guest_sign_in'

end



end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :disorder, length: { minimum: 2, maximum: 50 }
  validates :express, length: { maximum: 200 }


  scope :only_active, -> { where(is_active: true) }


  def follow(end_user)
    relationships.create(followed_id: end_user.id)
  end

  def unfollow(end_user)
    relationships.find_by(followed_id: end_user.id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      EndUser.where(name: content)
    elsif method == 'forward'
      EndUser.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      EndUser.where('name LIKE ?', '%' + content)
    else
      EndUser.where('name LIKE ?', '%' + content + '%')
    end
  end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :end_user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :end_user_id


end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :end_user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:500}

  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%'+content)
    else
      Post.where('title LIKE ?', '%'+content+'%')
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

    belongs_to :end_user
    belongs_to :post

    validates :comment, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"

end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
 before_action :authenticate_admin!
 before_action :ensure_correct_admin, only: [:update,:edit,:destroy]


  def new
   @post = Post.new
  end

  def show
    @end_user = EndUser.find(params[:id])
    @posts = @end_user.posts
    @post = Post.new
  end

  def index
    @end_users = EndUser.all
    @post = Post.new
    @end_user = current_end_user
  end

  def edit

  end

  def update
    @end_user = end_user.find(params[:id])
    @end_user.update(end_user_params)
   if @end_user.save
      flash[:notice]='　　You have updated end_user successfully.'
      redirect_to end_user_path(@end_user.id)
   else
      render :edit
   end
  end

  def destroy
    @end_user = EndUser.find(params[:id])
    @end_user.destroy
    redirect_to admin_end_users_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end




  private

  def end_user_params
    params.require(:end_user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_admin
    @admin = admin.find(params[:id])
    unless @admin == current_admin
      redirect_to admin_end_users_path(current_admin)
    end
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @end_users = EndUser.all
    @posts = Post.all
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @end_user = EndUser.find_by(params[post_id])

  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/end_users/index.html.1.erb
<table class='table table-hover table-inverse'>
<h2>　　利用者一覧</h2> <h5>　　アクティブユーザー数：　<%= @end_users.count %>　人</h5>
  <thead>
    <tr>
      <th>画像</th>
      <th>会員名</th>
      <th>伝えたい事</th>
      <th>障害名</th>
      <th>メールアドレス</th>
      <th>年代</th>
      <th>性別</th>
      <th>都道府県</th>
      <th>パスワード</th>
      <th>社会に希望する事</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
      <th>投稿数</th>
      <th>退会可否</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @end_users.each do |end_user| %>
      <tr>
        <td><%= image_tag end_user.get_profile_image(50,50) %></td>
        <td><%= end_user.name %></td>
        <td><%= end_user.express %></td>
        <td><%= end_user.disorder %></td>
        <td><%= end_user.email %></td>
        <td><%= end_user.age %></td>
        <td><%= end_user.sex %></td>
        <td><%= end_user.prefecture %></td>
        <td><%= end_user.password %></td>
        <td><%= end_user.want %></td>
        <td><%= end_user.followings.count %></td>
        <td><%= end_user.followers.count %></td>
        <td><%= end_user.posts.count %></td>
        <td><% if end_user.is_active? %>
						<span class="text-active">有効</span>
					<% else %>
						<span class="text-invalid">退会済み</span>
					<% end %>
        </td>
        <td><#%= link_to '削除', withdraw_end_user_path,  class: "end_user_#{end_user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/end_users/index.html.erb
<table class='table table-hover table-inverse'>
<h2>　　利用者一覧</h2> <h5>　　アクティブユーザー数：　<%= @end_users.count %>　人</h5>
  <thead>
    <tr class="sticky-top">
      <th>画像</th>
      <th>会員名</th>
      <th>障害名</th>
      <th>メールアドレス</th>
      <th>年代</th>
      <th>性別</th>
      <th>都道府県</th>
      <th>パスワード</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
      <th>投稿数</th>
      <th>退会可否</th>
    </tr>
  </thead>
  <tbody>
    <% @end_users.each do |end_user| %>
      <tr>
        <td rowspan="3"><%= image_tag end_user.get_profile_image(50,50) %></td>
        <td><%= end_user.name %></td>
        <td><%= end_user.disorder %></td>
        <td><%= end_user.email %></td>
        <td><%= end_user.age %></td>
        <td><%= end_user.sex %></td>
        <td><%= end_user.prefecture %></td>
        <td><%= end_user.password %></td>
        <td></td>
        <td><%= end_user.followings.count %></td>
        <td><%= end_user.followers.count %></td>
        <td><%= end_user.posts.count %></td>
        <td><% if end_user.is_active? %>
						<span class="text-active">有効</span>
					<% else %>
						<span class="text-invalid">退会済み</span>
					<% end %>
        </td>
      </tr>
      <tr>
        <td colspan="10">伝えたい事 : <%= end_user.express %></td>
      </tr>
      <tr>
        <td colspan="10">社会に希望する事 : <%= end_user.want %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<br><br><br>

app/views/admin/end_users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>
  <tr><%= image_tag @end_user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= @end_user.name %></th>
  </tr>
  <tr>
	  <th>disorder</th>
	  <th><%= @end_user.disorder %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @end_user.express %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to @end_user.followings.count, end_user_followings_path(@end_user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to @end_user.followers.count, end_user_followers_path(@end_user) %></th>
  </tr>
</table>
</div>
      <h2 class="mt-3"></h2>
    </div>

<div class='col-md-8 offset-md-1'>
<h2>Posts</h2>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
      <th></th>
      <th>タイトル</th>
      <th>投稿</th>
      <th>いいね数</th>
      <th>コメント数</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to end_user_path(post.end_user.id) do %>
          <%= image_tag post.end_user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to post.title,post, class: "post_#{post.id}" %></td>
        <td><%= post.body %></td>
        <td><%= post.favorites.count %></td>
        <td><%= render "public/post_comments/counter", post: post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
</div>
<br>
<br>
<br>
<br>