config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :end_users, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]

    resources :post_comments, only: [:destroy]

     get '/search', to: 'searches#search'

  end


  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}




 scope module: :public do
  root to: 'homes#top'
  get "/home/about" => "homes#about"


  get 'end_users/unsubscribe' => 'end_users#unsubscribe', as: 'confirm_unsubscribe'
  patch 'end_users/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'

  #post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  #post 'end_users/guest_sign_in'  => 'end_users/sessions#guest_sign_in'

  resources :end_users, only: [:index, :show, :edit,:update, :destroy] do
  resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  get '/search', to: 'searches#search'

  post '/guests/guest_sign_in', to: 'guests#guest_sign_in'

end



end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :disorder, length: { minimum: 2, maximum: 50 }
  validates :express, length: { maximum: 200 }


  scope :only_active, -> { where(is_active: true) }


  def follow(end_user)
    relationships.create(followed_id: end_user.id)
  end

  def unfollow(end_user)
    relationships.find_by(followed_id: end_user.id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      EndUser.where(name: content)
    elsif method == 'forward'
      EndUser.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      EndUser.where('name LIKE ?', '%' + content)
    else
      EndUser.where('name LIKE ?', '%' + content + '%')
    end
  end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :end_user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :end_user_id


end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :end_user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:500}

  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%'+content)
    else
      Post.where('title LIKE ?', '%'+content+'%')
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

    belongs_to :end_user
    belongs_to :post

    validates :comment, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"

end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @end_users = EndUser.all
    @posts = Post.all
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @end_user = EndUser.find_by(params[post_id])

  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header style="background-color:lightskyblue;"  class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bit Supporter Admin</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_top_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-candy-cane"></i> HomeAdmin
            <% end %>
          </li>
          <li>
            <%=  link_to admin_end_users_path,class: 'nav-link text-dark' do %>
              <i class="far fa-id-card"></i> 利用者一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_posts_path ,class: 'nav-link text-dark' do %>
              <i class="fas fa-file-signature"></i> 投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark' do %>
              <i class="fas fa-lock-open"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-candy-cane"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-hand-point-up"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to admin_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-lock"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Sur Communication Inc.
            <%= link_to admin_session_path do%><i class="fas fa-infinity"></i></div>
            <% end %>
    	      <% if end_user_signed_in? %>
              <div class="d-flex justify-content-center mb-2">
                <%= render 'public/searches/form' %>
                </div><% end %>
    	 </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-lightskyblue">
    <div class="container">
      <a class="navbar-brand p-2" href="/">
        <%= image_tag "Bit Supporter Logo-01small.png" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if end_user_signed_in? %>
          <li>
            <%= link_to end_user_path(current_end_user),class: 'nav-link text-light' do %>
              <i class="fas fa-candy-cane"></i> マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to end_users_path,class: 'nav-link text-light' do %>
              <i class="far fa-id-card"></i> 会員一覧
            <% end %>
          </li>
          <li>
            <%=  link_to posts_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-file-signature"></i> 投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_end_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-lock-open"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-candy-cane"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-hand-point-up"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_end_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-person-booth"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to end_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-lock"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
  <sidebar class="sticky-top">
    <!-- toggle section -->
    <input type="checkbox" id="check" />
    <label for="check">
      <i class="fas fa-bars" id="btn"></i>
      <i class="fas fa-times" id="cancel"></i>
    </label>
    <!-- sidebar section -->
    <div class="sidebar">
      <header><strong>投稿</strong></header>
        <% if end_user_signed_in? && @guestusername != "guestuser" %>
        <ul>
          <li>
            <%= form_with model:@post,local:true do |f| %>
            <div class="form-group">
            <%= f.label :タイトル %>
            <%= f.text_field :title, class: 'form-control post_title' %>
            </div>
            <div class="form-group">
            <%= f.label :投稿内容 %>
            <%= f.text_area :body, class: 'form-control post_body' %>
            </div>
            <div class="form-group">
            <%= f.submit "投稿する", class: 'btn btn-success' %>
            </div>
            <% end %>
            <% end %>
        </li>
        <li>
          <a href="https://www.ryotakaneda.com/contact">  <i class="fas fa-envelope"></i>　　　お問い合わせ</a>
        </li>
      </ul>
    </div>

  </sidebar>

app/views/layouts/application.html.1.erb
<!DOCTYPE html>
<html>
  <head class="sticky-top">
    <title>Bit Supporter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body style="background-color:deepskyblue;">
    <% if request.fullpath.include? "admin"  %>
      <%= render 'layouts/admin_header' %>
        <% else%>
        <%= render 'layouts/header' %>
       <sidebar>
        <%= render 'layouts/sidebar' %>
       </sidebar>
        <% end %>
      <main>
        <p id="notice">　　<%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class="sticky-top">
    <title>Bit Supporter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    　 <%#= favicon_link_tag('favicon.ico') %>
  </head>
    <body style="background-color:deepskyblue;">
    <% if request.fullpath.include? "admin"  %>
      <%= render 'layouts/admin_header' %>
        <% else%>
        <%= render 'layouts/header' %>
        <% if @is_post_show.blank? %>
          <%= render 'layouts/sidebar' %>
        <% end %>
        <% end %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>